"""Ledger entries - one side of a double-entry posting (`db_arch.md` section 24).

A `LedgerEntry` is either a debit or a credit, never both and never neither;
the database enforces that with check constraints. Money is `NUMERIC(14,2)`,
never Float, matching every other financial table in the project.

All lines generated by one business event share a `(reference_type,
reference_id)` pair, e.g. `("SALE", sale.id)`. That is the posting group, and
it is also the duplicate-post guard: a unique constraint on
`(shop_id, reference_type, reference_id, account_id)` lets one event post to
several accounts while making a second posting of the same event impossible.

There is no `updated_at`: a ledger entry is immutable once written. The
composite foreign key to `accounts` guarantees a ledger entry can only ever
point at an account in the same shop.
"""

import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Numeric,
    String,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, UUIDMixin

if TYPE_CHECKING:
    from app.models.account import Account
    from app.models.shop import Shop


class LedgerEntry(Base, UUIDMixin):
    """One debit or credit line of a posting group."""

    __tablename__ = "ledger_entries"

    __table_args__ = (
        # Tenant-safe account reference: the (account_id, shop_id) pair must
        # resolve to an account owned by the same shop. RESTRICT on purpose -
        # an account with ledger history must not be deletable in a way that
        # silently erases that history.
        ForeignKeyConstraint(
            ["account_id", "shop_id"],
            ["accounts.id", "accounts.shop_id"],
            name="fk_ledger_entries_account_same_shop",
            ondelete="RESTRICT",
        ),
        # Duplicate-post protection: an event may post to several accounts, but
        # never twice to the same account.
        UniqueConstraint(
            "shop_id",
            "reference_type",
            "reference_id",
            "account_id",
            name="uq_ledger_entries_reference_account",
        ),
        Index(
            "ix_ledger_entries_shop_account_created_at",
            "shop_id",
            "account_id",
            "created_at",
        ),
        Index(
            "ix_ledger_entries_shop_reference",
            "shop_id",
            "reference_type",
            "reference_id",
        ),
        CheckConstraint("debit >= 0", name="ck_ledger_entries_debit_non_negative"),
        CheckConstraint("credit >= 0", name="ck_ledger_entries_credit_non_negative"),
        CheckConstraint(
            "NOT (debit > 0 AND credit > 0)",
            name="ck_ledger_entries_single_sided",
        ),
        CheckConstraint("debit + credit > 0", name="ck_ledger_entries_non_zero"),
    )

    shop_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("shops.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
    )

    debit: Mapped[Decimal] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0"),
        server_default=text("0"),
    )

    credit: Mapped[Decimal] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0"),
        server_default=text("0"),
    )

    reference_type: Mapped[str] = mapped_column(String(50), nullable=False)

    reference_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )

    description: Mapped[str | None] = mapped_column(String(300))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    shop: Mapped["Shop"] = relationship(
        "Shop",
        back_populates="ledger_entries",
        overlaps="account,accounts,ledger_entries,shop",
    )

    account: Mapped["Account"] = relationship(
        "Account",
        back_populates="ledger_entries",
        overlaps="account,accounts,ledger_entries,shop",
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        return (
            f"LedgerEntry(id={self.id!r}, account_id={self.account_id!r}, "
            f"debit={self.debit!r}, credit={self.credit!r})"
        )